version: "3.5"

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=${RDS_CLIENT_ID}
      - MB_DB_PASS=${RDS_CLIENT_PWD}
      - MB_DB_HOST=<AWS_RDS_INSTANCE_URI>
      # EG: example.eu-west-2.rds.amazonaws.com
  nginx:
    restart: always
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - metabase